language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD
