language: node_js

node_js:
  - '14.5.0'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

after_success:
  gulp deploy --user "victor@ccsapp.dikeninternational.com" --password "LUDwig2639+"
