language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

after_success:
  "curl -T Dockerfile -u $FTP_USER:$FTP_PASSWORD ftp://192.232.238.157/public_html/"
